# config.yaml
paths:
  log_file: "execution_log.txt"
  model_id: "/root/Desktop/workspace/paper_summary/Meta-Llama-3.1-8B-Instruct"
  markdown_dir: "./markdown_files"
  log_file_path: "ai_summary_log.json"

slack:
  channel_name: "논문요약테스트"
  api_token: "api_token"
  signing_secret: "signing_secret"
