# config.yaml
paths:
  log_file: "execution_log.txt"
  model_id: "/root/Desktop/workspace/paper_summary/Meta-Llama-3.1-8B-Instruct"
  markdown_dir: "./markdown_files"
  log_file_path: "ai_summary_log.json"

slack:
  api_token: "your-slack-api-token-here"  # 이 값은 환경 변수로 설정할 수도 있음
  channel_name: "논문요약테스트"
